# -*- coding: utf-8 -*-
{
  "name": """POS Full Session Report Print""",
  "summary":"""This module prints POS S Printn ession Summary as well as send Session Summary to the current login user.""",
  "category":"Point Of Sale",
  "version": "11.0.0.0.1",
  "application": False,
  "author": "ERP World",
  "website" : "http://www.erpworld.ml",
  "support": "odoo_erp@zoho.com",
  "license": "LGPL-3",
  "depends" : ['point_of_sale','mail',],
  "data" : [
                            'views/pos_session_report_view.xml',
                             'views/report_session_summary.xml',
                             'views/pos_session_view.xml',
                             'edi/wk_session_report.xml',
                             'views/template.xml',
                             'views/pos_config_view.xml',
                            ],
  "images"               :  ['static/description/Banner.png'],
  "qweb"                 :  ['static/src/xml/pos_session_report.xml'],
  "installable"          :  True,
  "auto_install"         :  False,
  "pre_init_hook"        :  "pre_init_check",
}